# config/database.yml
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>  # Render Postgres
  cable:
    <<: *primary_production          # use the same DB for cable (simple + fine for demos)
